### ISSUE TITLE
Selection of User Network

### ISSUE THREAD

**Issue by susancoort** [CyTargetLinker/cytargetlinker.app#5]
When selecting User Network in the dialog "52:" is shown, why is this added to the name of the network?

**Comment by mkutmon** [comment]
I think, I'll add it after the name. It's the SUID of the network. That's important when you have to networks with the same name.

**Comment by susancoort** [comment]
Yes, you should number the created networks. because when you extend the network multiple times they are now all called "CTL_Network". I do like the highlighting in the sidepanel, here the SUID is shown.

**Comment by mkutmon** [comment]
Yes, I wasn't able to fully implement the cloning yet. Currently the original network stays the same and one extended network is created. Every extension afterwards is done in the same extended network. I added a issue to add this feature (clone = true/false) and will implement it in the future - but not before tomorrow.
