### ISSUE TITLE
Identifier column

### ISSUE THREAD

**Issue by susancoort** [CyTargetLinker/cytargetlinker.app#6]
I created a network of two nodes. I put the ENS id in the “name” column and left the node 1/2 under "shared name". I selected the "name" column when extending and than the extension doesn't work. When I put the ENS id in the "shared name" column and I select this column it works.

**Comment by mkutmon** [comment]
Thanks for reporting this. I can confirm that problem. I'll look into why that happens. It works with every column, except name. I'll try to find out what's going wrong.

**Comment by mkutmon** [comment]
see https://github.com/CyTargetLinker/cytargetlinker/issues/19
